### ISSUE TITLE
Pseudo code plan.

### ISSUE THREAD

**Issue by MarcoCacoete** [Tobyarmond/Object_Oriented_Assignment1#1]
Hi Toby, code LGTM good job!

Have you considered having a txt file with your planned out program in pseudo code to use as a reference?

Might increase your productivity.

Cheers.

**Comment by Tobyarmond** [comment]
Hi Marco, thanks for the suggestion, I think Pseudo code at this stage may be a bit redundant. Instead I've updated all the comments within the project to make it easier to understand.

**Comment by MarcoCacoete** [comment]
Ah I see, well it's always a good idea to write some pseudo code at the start of a project, it helps me structure my ideas better personally.

Have you accounted for null returns? Have a plan on how to handle them?

For my testing class I implemented a list to hold all dealt cards so far, it's easy enough to implement if you want to add some functionality.

Seems like your project is pretty well done from my perspective, kudos.
